# GitLab CI/CD Pipeline for Deploying with rsync

# このパイプラインで使用するステージを定義
stages:
  - build
  - deploy

# ビルドジョブ
build_job:
  stage: build
  image: node:latest
  tags:
    - web
  script:
    - npm install # または yarn install
    - npm run build # next.config.jsでoutput: 'export'を設定している場合はこのコマンドで out/ にビルドされます
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  only:
    - main # デプロイをトリガーするブランチ名に合わせて修正してください
    - master # 必要に応じて他のブランチやタグを追加

# デプロイジョブ
deploy_job:
  stage: deploy
  tags:
    - web
    - ssh
  image: alpine:latest # rsyncとsshコマンドが使える軽量イメージ
  dependencies:
    - build_job # ビルドジョブの成果物に依存
  script:
    # rsyncコマンドでデプロイ
    # -z: 圧縮転送, -a: アーカイブモード (パーミッションなどを維持), -v: 詳細表示, --delete: 転送元にないファイルを転送先から削除
    - rsync -zav --delete dist/ ubuntu:/var/www/youkan.uk/
      # ^^^ # ビルド成果物ディレクトリのパスを dist/ に修正
      #     ^^^^^^^^^^^ # デプロイ先のサーバーユーザーとホスト名を直接指定 (必要に応じて環境変数に戻してください)
      #                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ # デプロイ先のパス
  only:
    - main # デプロイをトリガーするブランチ名に合わせて修正してください
    - master # 必要に応じて他のブランチやタグを追加 